import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

interface Message {
    role: string;
    content: string;
}

export const generateMedicalReport = (
    patientName: string,
    date: string,
    transcript: Message[]
) => {
    const doc = new jsPDF();

    // Header
    doc.setFontSize(22);
    doc.setTextColor(41, 108, 188); // Primary Blue
    doc.text("Pixal Health - Medical Consultation Report", 14, 20);

    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`Generated on: ${new Date().toLocaleString()}`, 14, 28);

    // Patient Info Frame
    doc.setDrawColor(200);
    doc.setFillColor(250, 250, 252);
    doc.roundedRect(14, 35, 180, 25, 3, 3, 'FD');

    doc.setFontSize(12);
    doc.setTextColor(50);
    doc.text(`Patient Name: ${patientName}`, 20, 45);
    doc.text(`Session Date: ${date}`, 20, 52);

    // Disclaimer
    doc.setFontSize(9);
    doc.setTextColor(220, 53, 69); // Red
    doc.text("MEDICAL DISCLAIMER: This report is generated by an AI assistant and does not constitute a professional medical diagnosis. Please consult a qualified healthcare provider for official medical advice.", 14, 70, { maxWidth: 180 });

    // Transcript Table
    const tableData = transcript.map(msg => [
        msg.role === 'user' ? 'Patient' : 'Dr. Pixal (AI)',
        msg.content
    ]);

    autoTable(doc, {
        startY: 80,
        head: [['Speaker', 'Message']],
        body: tableData,
        theme: 'grid',
        styles: { fontSize: 10, cellPadding: 4 },
        headStyles: { fillColor: [41, 108, 188], textColor: 255 },
        columnStyles: {
            0: { cellWidth: 30, fontStyle: 'bold' },
            1: { cellWidth: 'auto' }
        },
        alternateRowStyles: { fillColor: [245, 247, 250] }
    });

    // Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text("Pixal Health AI - Empowering Your Health Journey", 14, pageHeight - 10);

    doc.save(`Pixal_Health_Report_${date.replace(/[\/:\s]/g, '_')}.pdf`);
};
